### ISSUE TITLE
Supporting Android 14+ regional settings

### ISSUE THREAD

**Issue by orestesgaolin** [ncosgray/region_settings#1]
I think it would be amazing to support Android 14+ regional settings like temperature or first day of the week

https://proandroiddev.com/regional-preferences-android14-c3e90a01e65f

**Comment by ncosgray** [comment]
Thank you for your interest in this plugin!

The plugin's `getTemperatureUnits()` function will indeed use the OS regional settings if available, which is currently supported on iOS and Android 14+. This value is accessible in `RegionSettings.temperatureUnits`.

I do have adding number format on my to-do list, as I personally have a use case for it. I'm happy to implement first day of the week as well -- should be quite straightforward to do that! Stay tuned.

**Comment by ncosgray** [comment]
Thanks again! [Version 1.1.0](https://github.com/ncosgray/region_settings/blob/main/CHANGELOG.md) adds support for finding the first day of the week from device region settings.
