### ISSUE TITLE
Support get number format set by the user in the iOS regional settings

### ISSUE THREAD

**Issue by tuyennvt** [ncosgray/region_settings#3]
![Group 18089](https://github.com/user-attachments/assets/7eb41980-b08b-4995-8d80-46429cb79356)
Currently, in the region settings on iOS, users can change the number format. It seems to be newly added in iOS 18. Can you support this feature in the package? Thanks very much

**Comment by ncosgray** [comment]
Great idea! I'm publishing version 1.2.0 shortly, which adds some basic support for regional number formats (integers and decimals).

Thanks so much for the suggestion. Please let me know if you think of anything else to add to this plugin.
